### ISSUE TITLE
Leading slash in containernames

### ISSUE THREAD

**Issue by brase** [kevinjqiu/coredns-dockerdiscovery#10]
Hi,

I tried your plugin but for some reason there is a leading slash in every container name.

As a quick fix for me, I trimmed it away but where does it come from?

I am a go noob. So maybe the answer is a simple one.

Thats the repo In which I have fixed it the naiv way: 
https://github.com/rheinspree/coredns-dockerdiscovery

Thank you,
Sebastian

PS: I also had to change one line due to a interface change in coredns.

**Comment by kevinjqiu** [comment]
Hi @brase  

This is actually how docker container names are internally.  This [comment](https://github.com/moby/moby/issues/6705#issuecomment-47298276) has more details.

Cheers,

**Comment by brase** [comment]
Okay, but then I should send you a PR because `/my-alpine.docker.loc` is not what is documented in the readme (`my-alpine.docker.loc`).

**Comment by kevinjqiu** [comment]
Sure, thanks.
