### ISSUE TITLE
Would this support Docker Swarm?

### ISSUE THREAD

**Issue by Leopere** [kevinjqiu/coredns-dockerdiscovery#14]
Will this work in a Docker Swarm setup?

My goal is to have dynamically defined A records pointing at Traefik reverse proxy instances.

**Comment by kevinjqiu** [comment]
I'm sorry I'm not familiar with how docker swarm does DNS and service
discovery. Maybe someone with more docker swarm experience can chime in.

**Comment by Leopere** [comment]
I believe it’s mostly the same I know Traefik should have an example.
